name: Deploy
on:
  push:
    branches: [ master, prod ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up SSH
        run: |
          mkdir -p ~/.ssh/
          echo "$SSH_PRIVATE_KEY" > ~/.ssh/id_rsa
          sudo chmod 600 ~/.ssh/id_rsa
          echo "$SSH_KNOWN_HOSTS" > ~/.ssh/known_hosts
        shell: bash
        env:
          SSH_PRIVATE_KEY: ${{secrets.SSH_PRIVATE_KEY}}
          SSH_KNOWN_HOSTS: ${{secrets.SSH_KNOWN_HOSTS}}

      - name: Install PM2
        run: npm i -g pm2
      - name: Install dependencies
        run: npm install

      - name: Deploy to Dev
        run: pm2 deploy development
        if: github.ref == 'refs/heads/master'
      - name: Deploy to Prod
        run: pm2 deploy production
        if: github.ref == 'refs/heads/prod'